// Copyright (c) 2026 Artyom Lazyan. All rights reserved.
// SPDX-License-Identifier: LicenseRef-SwarmKit-Proprietary
//
// This file is part of SwarmKit.
// See LICENSE.md in the repository root for full license terms.

#include "usage.h"

#include <iostream>

namespace swarmkit::apps::cli::internal {

void PrintUsage() {
    std::cout
        << "Usage: swarmkit-cli [ADDRESS] COMMAND [OPTIONS]\n"
           "\n"
           "  ADDRESS   Agent address, default: 127.0.0.1:50061\n"
           "\n"
           "Commands:\n"
           "  ping                   Send a ping and print the agent response.\n"
           "  health                 Read agent health/readiness.\n"
           "  preflight              Check connection, health, GPS, EKF, battery, and readiness.\n"
           "  stats                  Read agent runtime counters.\n"
           "  capabilities           Discover backend/autopilot feature support.\n"
           "  telemetry              Subscribe to telemetry and print frames.\n"
           "                         Press Ctrl+C to stop.\n"
           "  command                Send a command with selected priority.\n"
           "  sequence               Run command steps from a YAML file.\n"
           "  trajectory             Upload, validate, prepare, start, and monitor timed paths.\n"
           "  goal                   Set/cancel/read a supervised active goal.\n"
           "  reports                Subscribe to typed agent reports.\n"
           "  message                Publish/subscribe small generic data messages.\n"
           "  artifact               Upload/download/announce binary artifacts.\n"
           "  lock                   Acquire command authority for one drone.\n"
           "  unlock                 Release command authority for one drone.\n"
           "  watch-authority        Watch authority changes for one drone.\n"
           "  swarm                  Use a swarm config for control and telemetry workflows.\n"
           "\n"
           "Global options:\n"
           "  --config PATH          Load client config from YAML file\n"
           "  --client-id ID         Client identity for authority and data source_id\n"
           "  --ca-cert PATH         mTLS CA certificate path\n"
           "  --client-cert PATH     mTLS client certificate path\n"
           "  --client-key PATH      mTLS client private key path\n"
           "  --server-name NAME     TLS server name / authority override\n"
           "  --transport-security MODE\n"
           "                         auto|insecure|tls|mtls (default: auto)\n"
           "  --insecure             Shortcut for --transport-security insecure\n"
           "  --priority LEVEL       operator|supervisor|override|emergency\n"
           "  --min-battery PCT      Minimum battery percent for preflight (default: 20)\n"
           "  --log-sink TYPE        stdout|file|both for SDK/runtime logs\n"
           "  --log-file PATH        Rotating log file path when file logging is used\n"
           "  --log-level LEVEL      trace|debug|info|warn|error|critical|off\n"
           "\n"
           "Telemetry options:\n"
           "  --drone  DRONE_ID      Drone to subscribe to (default: default)\n"
           "  --rate   HZ            Frames per second     (default: 1)\n"
           "  --telemetry-file PATH  Append telemetry CSV to PATH\n"
           "  --telemetry-dir DIR    With swarm telemetry, write one CSV per drone\n"
           "  --no-console           Do not print telemetry frames to stdout\n"
           "  --duration-ms MS       Stop telemetry after a fixed duration\n"
           "\n"
           "Command options:\n"
           "  --drone  DRONE_ID      Target drone (default: default)\n"
           "  --verify               Wait until health/telemetry proves command completion\n"
           "  --timeout-ms MS        Verification timeout for --verify or verified sequence steps\n"
           "  --continue-on-error    For swarm commands, accept partial success\n"
           "  --require-all          For swarm commands, require every drone to succeed\n"
           "  Note: already-satisfied command replies are successful idempotent outcomes\n"
           "  arm                    Arm motors\n"
           "  disarm                 Disarm motors\n"
           "  land                   Land in place\n"
           "  hold                   Hold current position\n"
           "  return-home            Return to home\n"
           "  takeoff [--alt M]      Take off to altitude in metres (default: 10)\n"
           "  waypoint --lat L --lon L --alt M [--speed S]\n"
           "                         Fly to GPS waypoint\n"
           "  set-mode --mode stabilize|acro|guided|guided-nogps|loiter|auto|rtl|land|brake\n"
           "           [--custom-mode N]\n"
           "  set-speed --ground MPS\n"
           "  goto --lat L --lon L --alt M [--speed S] [--yaw DEG]\n"
           "  pause | resume\n"
           "  set-yaw --deg DEG [--rate DEG_S] [--relative]\n"
           "  velocity --vx N --vy E --vz D [--duration-ms MS] [--body-frame]\n"
           "  emergency force-arm | emergency force-disarm | emergency flight-terminate\n"
           "  set-home current | set-home --lat L --lon L --alt M\n"
           "  mission upload --file mission.yaml | mission clear | mission start\n"
           "  mission pause | mission resume | mission set-current --seq N\n"
           "  backend-command --namespace NS --name NAME [--param key=value]\n"
           "                         Backend-specific extension escape hatch\n"
           "  photo | photo-interval-start | photo-interval-stop | video-start | video-stop\n"
           "  gimbal-point | roi-location | roi-clear | servo | relay | gripper\n"
           "  sequence --file plan.yaml [--drone DRONE_ID]\n"
           "                         Run local automation steps from YAML\n"
           "  trajectory upload --file path.yaml|path.jsonl|path.csv [--format auto|yaml|jsonl|csv]\n"
           "  trajectory validate --file path.yaml|path.jsonl|path.csv\n"
           "  trajectory prepare --execution-id ID\n"
           "  trajectory start-at --execution-id ID [--unix-time-ms T]\n"
           "  trajectory pause|resume|abort|clear|get --execution-id ID\n"
           "  trajectory list | trajectory time-sync | trajectory reports\n"
           "\n"
           "Goal options:\n"
           "  goal set --goal-id ID --lat L --lon L --alt M [--revision N]\n"
           "  goal set --goal-id ID --frame local-ned --x M --y M --z M\n"
           "           [--speed MPS] [--accept-radius M] [--deviation-radius M]\n"
           "           [--timeout-ms MS] [--label KEY=VALUE ...]\n"
           "  goal cancel [--goal-id ID]\n"
           "  goal get\n"
           "\n"
           "Report options:\n"
           "  reports --drone DRONE_ID|all [--format text|jsonl]\n"
           "          [--report-file PATH] [--after-sequence N] [--duration-ms MS]\n"
           "\n"
           "Data options:\n"
           "  message publish --topic TOPIC [--target ID] [--payload TEXT|--file PATH]\n"
           "  message send --topic TOPIC --target DRONE_ID [--payload TEXT|--file PATH]\n"
           "                  [--duration-ms TTL_MS] [--label KEY=VALUE ...]\n"
           "  message subscribe [--topic TOPIC ...] [--target ID]\n"
           "                    [--after-sequence N] [--duration-ms MS]\n"
           "                    Without --target, targeted messages for another id are hidden.\n"
           "  message peers [--refresh]\n"
           "  artifact upload --file PATH [--content-type TYPE] [--target ID]\n"
           "  artifact send --file PATH --target DRONE_ID [--content-type TYPE]\n"
           "                  [--chunk-bytes N] [--duration-ms TTL_MS] [--label KEY=VALUE ...]\n"
           "  artifact start --file PATH [--target DRONE_ID] [--route]\n"
           "                  [--chunk-bytes N] [--duration-ms TTL_MS] [--label KEY=VALUE ...]\n"
           "  artifact status --transfer-id ID | artifact cancel --transfer-id ID\n"
           "  artifact download --artifact-id ID --file PATH\n"
           "  artifact announce --artifact-id ID [--target ID] [--content-type TYPE]\n"
           "\n"
           "Authority options:\n"
           "  --ttl-ms MS            Lock TTL; 0 means no automatic expiry\n"
           "\n"
           "Swarm options:\n"
           "  --swarm-config PATH    YAML fleet config for swarm commands\n"
           "  --address-mode MODE    primary|local (default: primary)\n"
           "  swarm health           Read health from every configured agent\n"
           "  swarm stats            Read runtime stats from every configured agent\n"
           "  swarm telemetry        Subscribe to all drones, or --drone DRONE_ID\n"
           "  swarm command --drone D ACTION...\n"
           "                         Route one command through the swarm config\n"
           "  swarm broadcast ACTION...\n"
           "                         Send one command to every configured drone\n"
           "  swarm ... --verify     Verify routed/broadcast commands per drone\n"
           "  swarm ... --continue-on-error\n"
           "                         Exit successfully when at least one drone reaches acceptable state\n"
           "  swarm sequence --file plan.yaml\n"
           "                         Run per-drone/broadcast automation steps from YAML\n"
           "\n"
           "Sequence YAML:\n"
           "  steps:\n"
           "    - args: [set-mode, --mode, guided]\n"
           "    - broadcast: true\n"
           "      args: [takeoff, --alt, 5]\n"
           "      verify: true\n"
           "    - drone: drone-1\n"
           "      args: [goto, --lat, -35.363, --lon, 149.1655, --alt, 5]\n"
           "      verify: true\n"
           "    - drone: drone-1\n"
           "      wait_position: {lat: -35.363, lon: 149.1655, alt: 5, radius_m: 2}\n"
           "      timeout_ms: 60000\n"
           "    - broadcast: true\n"
           "      wait_battery_min: 30\n"
           "      wait_heartbeat: true\n"
           "    - broadcast: true\n"
           "      args: [disarm]\n"
           "      retries: 10\n"
           "      retry_delay_ms: 2000\n"
           "    - delay_ms: 1000\n"
           "\n"
           "Trajectory YAML:\n"
           "  execution_id: path-1\n"
           "  drone_id: uav-1\n"
           "  validation: {min_battery_percent: 30, require_gps: true, max_altitude_m: 120}\n"
           "  points:\n"
           "    - {time_offset_ms: 0, lat: 40.18, lon: 44.51, alt: 10, yaw: 90}\n"
           "    - {time_offset_ms: 5000, lat: 40.1801, lon: 44.5101, alt: 12}\n"
           "\n"
           "Trajectory JSONL:\n"
           "  {\"execution_id\":\"path-1\",\"drone_id\":\"uav-1\",\"frame\":\"global\"}\n"
           "  {\"time_offset_ms\":0,\"lat\":40.18,\"lon\":44.51,\"alt_m\":10,\"yaw_deg\":90}\n"
           "  {\"time_offset_ms\":5000,\"lat\":40.1801,\"lon\":44.5101,\"alt_m\":12}\n"
           "\n"
           "Trajectory CSV:\n"
           "  time_offset_ms,lat,lon,alt_m,yaw_deg\n"
           "  0,40.18,44.51,10,90\n"
           "  5000,40.1801,44.5101,12,\n"
           "\n"
           "Examples:\n"
           "  swarmkit-cli ping\n"
           "  swarmkit-cli 192.168.1.10:50061 ping\n"
           "  swarmkit-cli telemetry --drone uav-1 --rate 2\n"
           "  swarmkit-cli preflight --drone uav-1 --duration-ms 3000 --min-battery 25\n"
           "  swarmkit-cli command --drone uav-1 arm\n"
           "  swarmkit-cli command --drone uav-1 takeoff --alt 30 --verify --timeout-ms 60000\n"
           "  swarmkit-cli command --drone uav-1 goto --lat 40.18 --lon 44.51 --alt 50\n"
           "  swarmkit-cli command --drone uav-1 backend-command --namespace mavlink "
           "--name command-long --param command=511 --param param1=33\n"
           "  swarmkit-cli goal --drone uav-1 set --goal-id node-42 --lat 40.18 --lon 44.51 "
           "--alt 50 --label route=node-42\n"
           "  swarmkit-cli message publish --topic rotor.event --payload '{\"event\":\"ok\"}'\n"
           "  swarmkit-cli artifact upload --file frame.jpg --content-type image/jpeg\n"
           "  swarmkit-cli reports --drone uav-1 --format jsonl\n"
           "  swarmkit-cli trajectory upload --drone uav-1 --file path.yaml\n"
           "  swarmkit-cli trajectory upload --drone uav-1 --file path.jsonl --format jsonl\n"
           "  swarmkit-cli trajectory start-at --drone uav-1 --execution-id path-1 "
           "--unix-time-ms 0\n"
           "  swarmkit-cli telemetry --drone uav-1 --rate 5 --telemetry-file uav-1.csv\n"
           "  swarmkit-cli lock --drone uav-1 --ttl-ms 10000\n"
           "  swarmkit-cli swarm --swarm-config testdata/swarm_config.yaml broadcast takeoff "
           "--alt 5 --verify --timeout-ms 60000\n"
           "  swarmkit-cli swarm --swarm-config testdata/swarm_config.yaml sequence "
           "--file plan.yaml\n"
           "  swarmkit-cli swarm --swarm-config testdata/swarm_config.yaml telemetry "
           "--telemetry-dir logs\n";
}

}  // namespace swarmkit::apps::cli::internal
