// Copyright (c) 2026 Artyom Lazyan. All rights reserved.
// SPDX-License-Identifier: LicenseRef-SwarmKit-Proprietary
//
// This file is part of SwarmKit.
// See LICENSE.md in the repository root for full license terms.

#include "usage.h"

#include <iostream>

namespace swarmkit::apps::cli::internal {

void PrintUsage() {
    std::cout
        << "Usage: swarmkit-cli [ADDRESS] COMMAND [OPTIONS]\n"
           "\n"
           "  ADDRESS   Agent address, default: 127.0.0.1:50061\n"
           "\n"
           "Commands:\n"
           "  ping                   Send a ping and print the agent response.\n"
           "  health                 Read agent health/readiness.\n"
           "  stats                  Read agent runtime counters.\n"
           "  telemetry              Subscribe to telemetry and print frames.\n"
           "                         Press Ctrl+C to stop.\n"
           "  command                Send a command with selected priority.\n"
           "  sequence               Run command steps from a YAML file.\n"
           "  lock                   Acquire command authority for one drone.\n"
           "  unlock                 Release command authority for one drone.\n"
           "  watch-authority        Watch authority changes for one drone.\n"
           "  swarm                  Use a swarm config for control and telemetry workflows.\n"
           "\n"
           "Global options:\n"
           "  --config PATH          Load client config from YAML file\n"
           "  --ca-cert PATH         mTLS CA certificate path\n"
           "  --client-cert PATH     mTLS client certificate path\n"
           "  --client-key PATH      mTLS client private key path\n"
           "  --server-name NAME     TLS server name / authority override\n"
           "  --priority LEVEL       operator|supervisor|override|emergency\n"
           "  --log-sink TYPE        stdout|file|both for SDK/runtime logs\n"
           "  --log-file PATH        Rotating log file path when file logging is used\n"
           "  --log-level LEVEL      trace|debug|info|warn|error|critical|off\n"
           "\n"
           "Telemetry options:\n"
           "  --drone  DRONE_ID      Drone to subscribe to (default: default)\n"
           "  --rate   HZ            Frames per second     (default: 1)\n"
           "  --telemetry-file PATH  Append telemetry CSV to PATH\n"
           "  --telemetry-dir DIR    With swarm telemetry, write one CSV per drone\n"
           "  --no-console           Do not print telemetry frames to stdout\n"
           "  --duration-ms MS       Stop telemetry after a fixed duration\n"
           "\n"
           "Command options:\n"
           "  --drone  DRONE_ID      Target drone (default: default)\n"
           "  arm                    Arm motors\n"
           "  disarm                 Disarm motors\n"
           "  land                   Land in place\n"
           "  hold                   Hold current position\n"
           "  return-home            Return to home\n"
           "  takeoff [--alt M]      Take off to altitude in metres (default: 10)\n"
           "  waypoint --lat L --lon L --alt M [--speed S]\n"
           "                         Fly to GPS waypoint\n"
           "  set-mode --mode guided|loiter|auto|rtl|land|brake [--custom-mode N]\n"
           "  set-speed --ground MPS\n"
           "  goto --lat L --lon L --alt M [--speed S] [--yaw DEG]\n"
           "  pause | resume\n"
           "  set-yaw --deg DEG [--rate DEG_S] [--relative]\n"
           "  velocity --vx N --vy E --vz D [--duration-ms MS] [--body-frame]\n"
           "  emergency force-disarm | emergency flight-terminate\n"
           "  set-home current | set-home --lat L --lon L --alt M\n"
           "  mission upload --file mission.yaml | mission clear | mission start\n"
           "  mission pause | mission resume | mission set-current --seq N\n"
           "  photo | photo-interval-start | photo-interval-stop | video-start | video-stop\n"
           "  gimbal-point | roi-location | roi-clear | servo | relay | gripper\n"
           "  sequence --file plan.yaml [--drone DRONE_ID]\n"
           "                         Run local automation steps from YAML\n"
           "\n"
           "Authority options:\n"
           "  --ttl-ms MS            Lock TTL; 0 means no automatic expiry\n"
           "\n"
           "Swarm options:\n"
           "  --swarm-config PATH    YAML fleet config for swarm commands\n"
           "  --address-mode MODE    primary|local (default: primary)\n"
           "  swarm health           Read health from every configured agent\n"
           "  swarm stats            Read runtime stats from every configured agent\n"
           "  swarm telemetry        Subscribe to all drones, or --drone DRONE_ID\n"
           "  swarm command --drone D ACTION...\n"
           "                         Route one command through the swarm config\n"
           "  swarm broadcast ACTION...\n"
           "                         Send one command to every configured drone\n"
           "  swarm sequence --file plan.yaml\n"
           "                         Run per-drone/broadcast automation steps from YAML\n"
           "\n"
           "Sequence YAML:\n"
           "  steps:\n"
           "    - args: [set-mode, --mode, guided]\n"
           "    - broadcast: true\n"
           "      args: [takeoff, --alt, 5]\n"
           "      verify: true\n"
           "    - drone: drone-1\n"
           "      args: [goto, --lat, -35.363, --lon, 149.1655, --alt, 5]\n"
           "      verify: true\n"
           "    - drone: drone-1\n"
           "      wait_position: {lat: -35.363, lon: 149.1655, alt: 5, radius_m: 2}\n"
           "      timeout_ms: 60000\n"
           "    - broadcast: true\n"
           "      wait_battery_min: 30\n"
           "      wait_heartbeat: true\n"
           "    - broadcast: true\n"
           "      args: [disarm]\n"
           "      retries: 10\n"
           "      retry_delay_ms: 2000\n"
           "    - delay_ms: 1000\n"
           "\n"
           "Examples:\n"
           "  swarmkit-cli ping\n"
           "  swarmkit-cli 192.168.1.10:50061 ping\n"
           "  swarmkit-cli telemetry --drone uav-1 --rate 2\n"
           "  swarmkit-cli command --drone uav-1 arm\n"
           "  swarmkit-cli command --drone uav-1 takeoff --alt 30\n"
           "  swarmkit-cli command --drone uav-1 goto --lat 40.18 --lon 44.51 --alt 50\n"
           "  swarmkit-cli telemetry --drone uav-1 --rate 5 --telemetry-file uav-1.csv\n"
           "  swarmkit-cli lock --drone uav-1 --ttl-ms 10000\n"
           "  swarmkit-cli swarm --swarm-config testdata/swarm_config.yaml broadcast takeoff "
           "--alt 5\n"
           "  swarmkit-cli swarm --swarm-config testdata/swarm_config.yaml sequence "
           "--file plan.yaml\n"
           "  swarmkit-cli swarm --swarm-config testdata/swarm_config.yaml telemetry "
           "--telemetry-dir logs\n";
}

}  // namespace swarmkit::apps::cli::internal
